/* ============================================================
   JobTrend365 — shared job category data
   Used by both index.html (category grid) and category.html
   (job detail pages). Edit this file to add, remove, or update
   job categories — both pages will update automatically.
   ============================================================ */

// Each icon is the *inner* markup of a 0 0 48 48 viewBox SVG,
// drawn as simple line icons (stroke = currentColor).
const ICONS = {
  box: '<rect x="8" y="14" width="32" height="26" rx="2"/><path d="M8 14 24 6l16 8"/><path d="M24 6v34"/>',
  van: '<rect x="4" y="17" width="26" height="15" rx="2"/><path d="M30 21h8l4 6v5h-12z"/><circle cx="13" cy="35" r="3.2"/><circle cx="33" cy="35" r="3.2"/>',
  headset: '<path d="M10 26v-2a14 14 0 0 1 28 0v2"/><rect x="6" y="24" width="8" height="12" rx="3"/><rect x="34" y="24" width="8" height="12" rx="3"/><path d="M38 36v1a5 5 0 0 1-5 5h-5"/>',
  pulse: '<circle cx="24" cy="24" r="18"/><path d="M14 24h5l3 6 4-12 3 6h5"/>',
  truck: '<rect x="4" y="20" width="20" height="14" rx="1.5"/><rect x="24" y="14" width="16" height="20" rx="1.5"/><path d="M24 21h5v6h-5z"/><circle cx="12" cy="36" r="3.2"/><circle cx="32" cy="36" r="3.2"/>',
  bag: '<path d="M10 16h28l-2.4 22a2 2 0 0 1-2 1.8H14.4a2 2 0 0 1-2-1.8z"/><path d="M16 16a8 8 0 0 1 16 0"/>',
  hat: '<path d="M8 30a16 16 0 0 1 32 0"/><rect x="5" y="30" width="38" height="5" rx="2.5"/><path d="M24 14v8"/>',
  monitor: '<rect x="6" y="9" width="36" height="24" rx="2"/><path d="M18 39h12M24 33v6"/><path d="M18 16l-4 5 4 5M30 16l4 5-4 5"/>',
  chef: '<path d="M14 22a6 6 0 0 1 4-10 6 6 0 0 1 6-4 6 6 0 0 1 6 4 6 6 0 0 1 4 10v6H14z"/><rect x="14" y="28" width="20" height="10" rx="1.5"/>',
  bucket: '<path d="M10 18c0-3.5 4.7-6 14-6s14 2.5 14 6"/><path d="M10 18h28l-3.2 20a3 3 0 0 1-3 2.6H16.2a3 3 0 0 1-3-2.6z"/>',
};

// Apply links use real job search engines, filtered by query + country.
function applyLinks(query) {
  const q = encodeURIComponent(query);
  return {
    uk: `https://uk.indeed.com/jobs?q=${q}`,
    us: `https://www.indeed.com/jobs?q=${q}`,
    ca: `https://ca.indeed.com/jobs?q=${q}`,
  };
}

const JOB_CATEGORIES = [
  {
    id: "warehouse-associate",
    rank: 1,
    title: "Warehouse & Fulfilment Associate",
    icon: ICONS.box,
    tagline: "Picking, packing and sorting roles at fulfilment centres",
    trend: "+38%",
    salary: { uk: "£21,500 – £27,500 / yr", us: "$32,000 – $42,000 / yr", ca: "C$34,000 – C$44,000 / yr" },
    about: "Online shopping keeps growing, and fulfilment centres in the UK, US and Canada need a steady flow of staff to pick, pack and sort orders. Shifts are flexible, training is provided on-site, and most positions can start within a week or two of applying — which is why this category is searched so heavily all year round.",
    responsibilities: [
      "Pick and pack customer orders accurately using a handheld scanner",
      "Sort, label and prepare parcels for dispatch",
      "Load and unload pallets and totes safely",
      "Keep your work area tidy and free of hazards",
      "Meet daily productivity and accuracy targets",
    ],
    requirements: [
      "Aged 18 or over",
      "Able to stand, walk and lift up to around 25kg / 55lb for a full shift",
      "Comfortable using a handheld scanner or simple app",
      "Reliable attendance and punctuality",
      "No prior warehouse experience required — training is provided",
    ],
    howToJoin: [
      "Check that you meet the age and physical requirements above.",
      "Update your CV or resume, including any retail, manual or stock-room experience.",
      "Apply through the official career site of a fulfilment operator, or use the search links below.",
      "Complete the short online application and any basic numeracy or scanning assessment.",
      "Attend orientation and safety training before your first shift on the floor.",
    ],
    apply: applyLinks("warehouse associate"),
  },
  {
    id: "delivery-driver",
    rank: 2,
    title: "Delivery & Courier Driver",
    icon: ICONS.van,
    tagline: "Last-mile parcel and food delivery, employed or self-employed",
    trend: "+45%",
    salary: { uk: "£22,000 – £29,500 / yr", us: "$35,000 – $48,000 / yr", ca: "C$36,000 – C$47,000 / yr" },
    about: "Same-day and next-day delivery has become normal, and courier networks across all three countries are constantly adding drivers for vans, cars and bikes. Many roles offer flexible routes or shift patterns, which makes this one of the fastest-rising searches of the year — particularly around peak shopping seasons.",
    responsibilities: [
      "Load your vehicle and follow an optimised delivery route",
      "Scan parcels and confirm proof of delivery using a driver app",
      "Handle packages carefully and follow safe-lifting practices",
      "Communicate politely with customers at the door",
      "Report any delays, damages or access issues promptly",
    ],
    requirements: [
      "Valid driving licence for your country (class depends on vehicle)",
      "A clean recent driving record",
      "Own or company vehicle, depending on the employer",
      "A smartphone for the delivery / routing app",
      "Aged 18+ (21+ for some larger vehicles)",
    ],
    howToJoin: [
      "Confirm your licence class covers the vehicle type the role needs.",
      "Gather your licence, insurance and right-to-work documents.",
      "Apply via the courier company's driver portal or the search links below.",
      "Complete a short driving history and background check.",
      "Attend a route briefing, then start your first scheduled shifts.",
    ],
    apply: applyLinks("delivery driver"),
  },
  {
    id: "customer-service-rep",
    rank: 3,
    title: "Customer Service Representative",
    icon: ICONS.headset,
    tagline: "Phone, chat and email support — office, hybrid or remote",
    trend: "+29%",
    salary: { uk: "£20,000 – £26,500 / yr", us: "$31,000 – $40,000 / yr", ca: "C$33,000 – C$42,000 / yr" },
    about: "As companies grow their contact-centre teams to cover phone, live chat and email, customer service roles remain one of the most reliable entry points into office-based work. Remote and hybrid options have made this category especially popular for people who want flexible hours without sacrificing stability.",
    responsibilities: [
      "Answer inbound calls, chats and emails from customers",
      "Resolve order, account and billing questions",
      "Log every interaction accurately in the CRM system",
      "Follow company scripts, tone guidelines and policies",
      "Escalate complex issues to specialist teams when needed",
    ],
    requirements: [
      "Aged 18 or over",
      "Clear spoken and written communication",
      "Basic computer literacy (typing, email, simple software)",
      "A quiet workspace if the role is remote",
      "Willingness to work shift patterns, including some evenings",
    ],
    howToJoin: [
      "Refresh your CV with any customer-facing, retail or phone experience.",
      "Complete any short typing or communication assessment the employer sends.",
      "Apply through the company's careers page or the search links below.",
      "Take part in a video or phone interview.",
      "Finish paid training before handling live calls or chats independently.",
    ],
    apply: applyLinks("customer service representative"),
  },
  {
    id: "care-assistant",
    rank: 4,
    title: "Healthcare & Care Assistant",
    icon: ICONS.pulse,
    tagline: "Supporting clients with daily living, in care homes or at home",
    trend: "+33%",
    salary: { uk: "£21,000 – £28,000 / yr", us: "$29,000 – $38,000 / yr", ca: "C$32,000 – C$41,000 / yr" },
    about: "Ageing populations and growing home-care services mean care assistant roles are searched constantly across the UK, US and Canada. Many employers offer paid training for people with no prior healthcare background, and the work is valued, steady and often close to home.",
    responsibilities: [
      "Support clients with daily living activities such as washing and dressing",
      "Assist with safe mobility, transfers and using equipment",
      "Monitor and record wellbeing, meals and activity",
      "Support medication reminders under guidance from a nurse or supervisor",
      "Communicate clearly with families and the wider care team",
    ],
    requirements: [
      "Aged 18 or over",
      "A patient, compassionate and reliable manner",
      "A basic care certificate, or willingness to complete one (often provided)",
      "A satisfactory background check (e.g. DBS, vulnerable sector check, or equivalent)",
      "Reliable transport for community-based roles",
    ],
    howToJoin: [
      "Check the entry-level certificate required in your region (for example, a care certificate, CNA or PSW course).",
      "Enrol in a short training course if you don't already hold one — many are free or employer-funded.",
      "Apply to care providers via the search links below.",
      "Complete the background check, references and a values-based interview.",
      "Start on supervised shifts before working more independently.",
    ],
    apply: applyLinks("care assistant"),
  },
  {
    id: "truck-driver",
    rank: 5,
    title: "HGV / CDL Truck Driver",
    icon: ICONS.truck,
    tagline: "Regional and long-haul freight driving for licensed drivers",
    trend: "+27%",
    salary: { uk: "£28,000 – £42,000 / yr", us: "$50,000 – $72,000 / yr", ca: "C$50,000 – C$70,000 / yr" },
    about: "Freight volumes keep climbing, and fleets are competing for licensed drivers with sign-on bonuses, route guarantees and training sponsorships. If you already hold (or are willing to train for) an HGV or CDL licence, this is one of the higher-paying categories on this list.",
    responsibilities: [
      "Drive and care for a heavy goods vehicle on assigned routes",
      "Complete pre-trip and post-trip vehicle inspections",
      "Load, unload or coordinate handovers with warehouse staff",
      "Keep accurate logs of hours, mileage and rest breaks",
      "Follow road safety rules and hours-of-service regulations",
    ],
    requirements: [
      "HGV / Class 1 licence (UK) or CDL Class A (US / Canada)",
      "A clean driving record",
      "A valid medical / driver fitness certificate where required",
      "Aged 21+ for most long-haul routes",
      "Willingness to be away from home overnight for some routes",
    ],
    howToJoin: [
      "Obtain or renew your HGV / CDL licence and medical certificate.",
      "Put together a short driving CV listing licence class and any endorsements.",
      "Apply directly to haulage or freight companies, or use the search links below.",
      "Pass the road test and background / medical checks.",
      "Complete company orientation and supervised route training.",
    ],
    apply: applyLinks("truck driver"),
  },
  {
    id: "retail-sales-associate",
    rank: 6,
    title: "Retail Sales Associate",
    icon: ICONS.bag,
    tagline: "Shop floor, till and stockroom roles in stores and malls",
    trend: "+22%",
    salary: { uk: "£18,500 – £24,000 / yr", us: "$26,500 – $34,500 / yr", ca: "C$29,000 – C$36,500 / yr" },
    about: "High-street and shopping-centre retailers post sales associate roles all year round, with extra demand around seasonal peaks. It's one of the most accessible jobs on this list and a popular first job for people entering the workforce.",
    responsibilities: [
      "Greet and assist customers on the shop floor",
      "Operate the till and handle cash or card payments",
      "Restock shelves and help with visual merchandising",
      "Process returns and exchanges following store policy",
      "Help keep the store clean, safe and well organised",
    ],
    requirements: [
      "Minimum working age varies by country and role (often 16+)",
      "A friendly, helpful manner with customers",
      "Basic maths for handling payments and change",
      "Ability to stand and move around for a full shift",
      "Flexible availability, including some weekends",
    ],
    howToJoin: [
      "Note any previous customer service, teamwork or retail experience on your CV.",
      "Apply directly via the retailer's careers page or the search links below.",
      "Complete a short in-store or video interview.",
      "Provide right-to-work documents and references.",
      "Complete till and product training before working on the floor unsupervised.",
    ],
    apply: applyLinks("retail sales associate"),
  },
  {
    id: "construction-labourer",
    rank: 7,
    title: "Construction Labourer",
    icon: ICONS.hat,
    tagline: "General site support for residential and infrastructure projects",
    trend: "+24%",
    salary: { uk: "£24,000 – £33,000 / yr", us: "$35,000 – $47,000 / yr", ca: "C$38,000 – C$50,000 / yr" },
    about: "New housing developments and infrastructure projects are creating steady demand for general labourers who support skilled trades on site. It's a hands-on way into the construction industry, with clear paths toward becoming a qualified tradesperson.",
    responsibilities: [
      "Prepare, clear and tidy work areas on site",
      "Move materials, tools and equipment safely",
      "Assist tradespeople such as carpenters and electricians",
      "Follow site safety procedures and wear required PPE at all times",
      "Carry out general site clean-up at the end of each day",
    ],
    requirements: [
      "Aged 18 or over",
      "Physically fit and comfortable with manual work outdoors",
      "Relevant site safety certification (e.g. a CSCS card in the UK, OSHA awareness training in the US, or the equivalent in Canada)",
      "Your own basic PPE — steel-toe boots, hi-vis vest and hard hat",
      "Reliable transport to the work site",
    ],
    howToJoin: [
      "Complete a basic site-safety course if you don't already hold a card.",
      "Gather your own PPE before applying.",
      "Apply to contractors or recruitment agencies via the search links below.",
      "Attend a site induction before your first day.",
      "Work under supervision while you build experience toward a trade.",
    ],
    apply: applyLinks("construction labourer"),
  },
  {
    id: "it-support-technician",
    rank: 8,
    title: "IT Support Technician",
    icon: ICONS.monitor,
    tagline: "Help-desk and on-site tech support — a popular entry into IT",
    trend: "+31%",
    salary: { uk: "£23,500 – £32,000 / yr", us: "$40,000 – $56,000 / yr", ca: "C$44,000 – C$58,000 / yr" },
    about: "As businesses rely more on laptops, cloud tools and remote work, help-desk and IT support roles remain one of the most-searched ways to start a career in tech — even without a computer science degree.",
    responsibilities: [
      "Respond to staff IT tickets by phone, chat or in person",
      "Troubleshoot hardware, software and network issues",
      "Set up and configure devices, accounts and software",
      "Document fixes clearly in the ticketing system",
      "Escalate complex issues to senior IT staff",
    ],
    requirements: [
      "Aged 18 or over",
      "Good problem-solving and communication skills",
      "Basic familiarity with Windows, macOS, Office or Google Workspace",
      "An entry-level certification such as CompTIA A+ is a plus, but not always required",
      "Willingness to learn new tools and systems quickly",
    ],
    howToJoin: [
      "Build a CV that highlights any troubleshooting, gaming-PC or tech-helper experience.",
      "Consider a free or low-cost entry certification, such as CompTIA A+ or Google IT Support.",
      "Apply via company careers pages or the search links below.",
      "Complete a technical screening or short practical test.",
      "Join a help-desk team with mentoring from senior technicians.",
    ],
    apply: applyLinks("IT support technician"),
  },
  {
    id: "food-service-crew",
    rank: 9,
    title: "Food Service Crew Member",
    icon: ICONS.chef,
    tagline: "Flexible part-time roles in restaurants, cafés and quick-service chains",
    trend: "+19%",
    salary: { uk: "£18,000 – £22,500 / yr", us: "$24,000 – $31,000 / yr", ca: "C$27,000 – C$33,500 / yr" },
    about: "Quick-service restaurants and cafés hire all year round, and shift patterns are often built around evenings and weekends — which makes this a favourite search for students and people looking for a flexible part-time job.",
    responsibilities: [
      "Prepare and serve food and drinks to company standards",
      "Take orders and operate the till",
      "Maintain food safety and hygiene standards at all times",
      "Clean and restock work stations throughout the shift",
      "Work as part of a fast-paced, supportive team",
    ],
    requirements: [
      "Minimum working age varies by country and state (often 16+)",
      "A food hygiene certificate — often provided as part of training",
      "Comfortable working evenings and/or weekends",
      "Ability to stay calm and organised during busy periods",
      "A team-player attitude",
    ],
    howToJoin: [
      "Check the minimum working age and any food-hygiene rules in your area.",
      "Apply directly through the restaurant's careers page or the search links below.",
      "Attend a short in-person or group interview.",
      "Complete food-safety and till training.",
      "Start on a part-time schedule with flexible shifts.",
    ],
    apply: applyLinks("food service crew member"),
  },
  {
    id: "cleaning-housekeeping",
    rank: 10,
    title: "Cleaning & Housekeeping Operative",
    icon: ICONS.bucket,
    tagline: "Office, hotel and residential cleaning — daytime or evening shifts",
    trend: "+21%",
    salary: { uk: "£19,000 – £24,000 / yr", us: "$26,000 – $33,500 / yr", ca: "C$28,000 – C$35,500 / yr" },
    about: "Offices, hotels and residential clients consistently search for reliable cleaning and housekeeping staff. Shifts are widely available throughout the day and evening, and many roles don't require previous experience.",
    responsibilities: [
      "Clean and sanitise assigned areas to an agreed standard",
      "Restock supplies such as soap, paper towels and linens",
      "Report any maintenance issues you notice",
      "Follow health and safety guidance for cleaning products and equipment",
      "Maintain a professional, discreet manner in client spaces",
    ],
    requirements: [
      "Aged 18 or over",
      "Good attention to detail",
      "Ability to work independently or as part of a small team",
      "Basic English for reading instructions and product labels",
      "A background check for some client sites (e.g. hospitals, offices)",
    ],
    howToJoin: [
      "List any previous cleaning, hospitality or facilities experience on your CV.",
      "Apply via cleaning contractors, hotels or the search links below.",
      "Attend a brief interview, sometimes including a site visit.",
      "Provide right-to-work documents and complete any required checks.",
      "Complete a short induction on chemicals, equipment and safety before starting.",
    ],
    apply: applyLinks("cleaner housekeeping"),
  },
];
